FROM php:8.2-fpm


RUN apt-get update && apt-get install -y \
    git zip unzip curl libpng-dev libonig-dev libxml2-dev \
    libzip-dev libpq-dev libicu-dev libmcrypt-dev \
    && docker-php-ext-install pdo pdo_mysql zip intl


COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

WORKDIR /var/www/html